version: '2'
services:
  postgres:
    image: postgres:13
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - default.env
      - production.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
